/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppCanvas: typeof import('./src/components/canvas/appCanvas.vue')['default']
    AppFooter: typeof import('./src/components/appFooter.vue')['default']
    AppHeader: typeof import('./src/components/appHeader.vue')['default']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
